#ifndef CONSTANTS_H
#define CONSTANTS_H

#include <windows.h>
#include <unordered_map>
#include <string>

// 定义颜色常量
const WORD DEFAULT_COLOR = FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE;
const WORD CODE_COLOR = FOREGROUND_RED | FOREGROUND_BLUE | FOREGROUND_INTENSITY;
const WORD YELLOW_COLOR = FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_INTENSITY;

// 多级标题颜色
const WORD HEADING1_COLOR = FOREGROUND_RED | FOREGROUND_INTENSITY; // 浅粉色
const WORD HEADING2_COLOR = FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_INTENSITY; // 粉色
const WORD HEADING3_COLOR = FOREGROUND_RED | FOREGROUND_BLUE | FOREGROUND_INTENSITY; // 深粉色
const WORD HEADING4_COLOR = FOREGROUND_GREEN | FOREGROUND_RED | FOREGROUND_BLUE | FOREGROUND_INTENSITY; // 更深色

const WORD GREEN_COLOR = FOREGROUND_GREEN | FOREGROUND_INTENSITY;
const WORD RED_COLOR = FOREGROUND_RED | FOREGROUND_INTENSITY;

// 语言到颜色映射
extern std::unordered_map<std::string, WORD> languageColorMap;

#endif // CONSTANTS_H
